// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgblmgkucmwbcrokqdty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnYmxtZ2t1Y213YmNyb2txZHR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNTYyNzksImV4cCI6MjA2MjkzMjI3OX0.0WszLwwN4VGWzBinrQxjA6TifWHSyOLggDpVPb6HoYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);